---
site_name: Bumper Docs
site_url: https://mvladislav.github.io/bumper
repo_url: https://github.com/MVladislav/bumper
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting Started:
      - DNS Setup: getting_started/dns.md
      - Certificate Setup: getting_started/certificates.md
  - Usage:
      - Command-Line Usage: usage/cli.md
      - Docker Usage: usage/docker.md
      - Mobile App Integration: usage/mobile_app.md
  - Configuration:
      - Environment Variables: configuration/environment.md
  - Internals:
      - Architecture: internals/architecture.md
      - Sniffing & Reverse Engineering: internals/sniffing.md
      - Certificate Pinning Bypass (APP): internals/certificate-unpinning-app.md
      - Certificate Pinning Bypass (BOT): internals/certificate-unpinning-bot.md
      - Certificate Pinning Bypass (GOAT): internals/certificate-unpinning-goat.md
  - Development:
      - Development Guide: development/dev-guide.md
      - Testing & CI: https://github.com/MVladislav/bumper/actions
  - Origins & Credits: origins.md

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: deep purple
  features:
    # - content.action.edit
    - content.code.copy
  logo: images/favicon.ico
  favicon: images/favicon.ico

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MVladislav/bumper

plugins:
  - privacy
  - search
  - glightbox
  # - social

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
